#!/bin/bash

if [[ -z "${PYTHON_EXEC}" ]]; then
  echo "PYTHON_EXEC being set to 'python'" 1>&2
  export PYTHON_EXEC="python"
fi

# stolen from stack overflow
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

(
cd $SCRIPT_DIR
$PYTHON_EXEC client.py "$1" < /dev/stdin &> /dev/stdout
)
